### PR TITLE
ISSUE 3: Added the new color pallets

### PR DESCRIPTION
**Pull request by dhwanishah**
Added the new color pallets according to specs

### CODE REVIEW

**Comment by dhwanishah** [comment]
STILL NEED TO FINALIZE THE NAME OF EACH OF THE COLOR PALLETS BEFORE THIS BRANCH IS COMPLETED AND MERGED.

**Comment by alfalfascout** [comment]
This all looks very good so far! Just a few notes:
- Try to make sure all the color choice swatches are easily visible against different backgrounds. For example, the dark purple swatch is almost invisible against the background of the white and gold variant.
- Try to make the swatches different enough from each other that it's clear they represent different color schemes. Actually, since there are so many color schemes now, maybe swatches should feature both button colors (one on each side of the swatch).
- The par.textContent field is for the user to see, so there should be spacing between "dark" and "green". (line 38 of colors.js)

**Comment by alfalfascout** [comment]
Also, more on the features side of things: would you swap some of the win colors? In the red black one, I'd prefer red for a winning color. In the yellow purple one, I would prefer purple. In the white and gold one, I would prefer white.

**Comment by dhwanishah** [comment]
Done. Check it out and merge if ready :)

**Comment by alfalfascout** [comment]
This is looking even better. Most of the splits look very neat, though a few of them have a line of background color through them(?).  Also, in the checkers scheme, the message text is almost invisible against the utils background. The others look great.

I can't help but think that there's probably a neater way to do the split backgrounds that wouldn't cause lines between them. I was thinking of using a right border about half the intended size of the swatch, though I'm not sure if the bordered area would also be clickable.

**Comment by dhwanishah** [comment]
capture

I'm not seeing the split as you are, so I'm confused as to why you're seeing it? Could you post a picture? 

Oh and oops I completely missed the message text color in the message...I'll change it to whitish color instead. But that means it's gonna be inconsistant :/

**Comment by alfalfascout** [comment]
screen shot 2015-10-05 at 11 24 53

It looks like this, to me. Isn't that strange?

**Comment by dhwanishah** [comment]
Hmm that's weird. Did you check those ones with the gap and compare them with the others using inspection in the browser? All the styling should've propagated to all elements

**Comment by alfalfascout** [comment]
They are all the same. Maybe it has to do with how the points & pixels are rendered on a retina screen (what I have). Maybe the spacing between them isn't exactly 5px, so it gets rendered inconsistently with a margin of -5px. That's my best guess.

**Comment by dhwanishah** [comment]
Hmm that's a possibility actually. I'll look into that cause I'm curious now. Nevertheless, I think this issue is pretty much resolved now if you wanna close it. Fyi...I changed the checkers theme message color.

**Comment by alfalfascout** [comment]
Rad! Thank you for all your hard work.

**Pull request closed without merging**
